name = "rankinglist-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "rankinglist-new"
database_id = "6d162793-9bc4-41f3-b414-3c1bc37532d0"

[[kv_namespaces]]
binding = "KV"
id = "67da8583a16f4fb8b39cd51f9f4dc089"

[env.production]
name = "rankinglist-api-prod"

[env.staging]
name = "rankinglist-api-staging"
